### ISSUE TITLE
Reading GridFS file line by line

### ISSUE THREAD

**Issue by xpepermint** [carrierwaveuploader/carrierwave-mongoid#116]
Let say I have 1GB file and I would like to read it line by line to save resources. Is it possible to do something like

``` ruby
Model.first.mountedfile.file.foreach do |line|
   ...
end
```

thx

**Comment by RachaBella** [comment]
Having the same issue right now ...

**Comment by rmm5t** [comment]
This might be a better question to bring up with https://github.com/mongoid/mongoid-grid_fs/

Howeer, I think the answer is as follows (untested):

```
Model.first.mountedfile.grid_file.each do |line|
  # ...
end
```
