### ISSUE TITLE
serializable_hash from carrierwave-mongoid overrides the default one

### ISSUE THREAD

**Issue by avaranovich** [carrierwaveuploader/carrierwave-mongoid#117]
Hello,

I have a strange issue

I want to tweak my models to return "id" in json.
I introduce this method

``` ruby
 def as_json do
          attrs = super(options)
          attrs["id"] = self._id
          attrs
end
```

super -- calls

ActiveModel::Serializers:as_json,

which has the following implementation

``` ruby
def as_json(options = nil)
        root = if options && options.key?(:root)
          options[:root]
        else
          include_root_in_json
        end

        if root
          root = self.class.model_name.element if root == true
          { root => serializable_hash(options) }
        else
          serializable_hash(options)
        end
      end
```

serializable_hash calls Carierware:Mongoid:serializable_hash, not the default one from mongoid

https://github.com/mongoid/mongoid/blob/5d8397e24b673724f4b70ca2923a62bfe20e6e79/lib/mongoid/serializable.rb#L37

the does include the uploaded, but I am I but puzzled, is that an indented behaviour?

**Comment by rmm5t** [comment]
Closing stale issues.
