### ISSUE TITLE
after_create callback  can not get the file path but the tmp file path.

### ISSUE THREAD

**Issue by hulkfu** [carrierwaveuploader/carrierwave-mongoid#129]
When use **after_create** callback in Rails, can not get the file path but the tmp file path.

Also look at [this guy on stackoverflow](http://stackoverflow.com/questions/5353743/callback-issue-with-carrierwave-and-mongoid).

This's my code:

``` ruby
class Task
  include Mongoid::Document

  after_create :do_something

  field :name, type: String

  mount_uploader :templete, TempleteUploader

  def do_something
    # When use templete.path will get '/app_root/public/uploads/tmp/1411548598-14576-1169/file'
    # So I use this to force get the path
    templete_path = File.expand_path("public/uploads/task/templete/#{id}/#{templete.file.filename}", Rails.root)
    process(templete_path)  
  end
end
```

Thanks!

**Comment by djunzu** [comment]
I just had a similar problem (maybe the same).
In my specific case, just changing `after_create :do_something` to `after_save :do_something, on: :create` solved the problem.

**Comment by h0jeZvgoxFepBQ2C** [comment]
This bug is still open, ```after_create``` returns the ```uploads/tmp``` path, which is clearly wrong for the ```after_create``` callback.

Also we can't use the ```after_commit``` callback, since [it has it's own kind of issues](https://github.com/rails/rails/pull/23462). So right now we can't use carrierwave properly unfortunately.

**Comment by ssoulless** [comment]
I can confirm that using `after_save` also returns the uploads/tmp path. I tried with `after_save :do_something, on: :create` after the `mount_uploader` but throwed this error:

`ArgumentError (Unknown key: :on. Valid keys are: :if, :unless, :prepend):`

**Comment by csrutil** [comment]
I got the same problem

**Comment by deanpcmad** [comment]
I'm currently running into this when using Turbo Broadcasts where it returns the `uploads/tmp` URL and not the correct uploaded URL. Any fix?
