### ISSUE TITLE
Rails 4 + Mongoid 4 + carrierwave-mongoid + 

### ISSUE THREAD

**Issue by patricklehmann** [carrierwaveuploader/carrierwave-mongoid#133]
Good evening,

i'm trying to migrate my image handling from paperclip to carrierwave. i'm on rails 4 with mongoid 4.
when i upload an image i get the following error:
BSON::Binary::InvalidType.

here are my gems...
gem 'mongoid', '~> 4', github: 'mongoid/mongoid'
gem 'bson'
gem 'bson_ext'
gem 'carrierwave'
gem 'mongoid-grid_fs', github: 'ahoward/mongoid-grid_fs'
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'moped', github: 'mongoid/moped'
gem 'mongoid_slug'
gem 'mongoid-app_settings'
gem 'mongo_session_store-rails3'
gem 'mongoid-observers'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'
gem 'mongoid_paranoia'
gem 'mongoid-tree'
gem 'mongoid-versioning', github: 'simi/mongoid-versioning'

can someone help in here? thaanks a lot!

kind regards, patrick

**Comment by victorsosa** [comment]
@vkeziah How do you do that?

> I fixed it by assigning subtype when storing the file into gridfs
