### ISSUE TITLE
TypeError - no implicit conversion of nil into String:

### ISSUE THREAD

**Issue by webmaster219** [carrierwaveuploader/carrierwave-mongoid#134]
I'm using now **ruby '2.1.4' and rails 4.1.0**
### Hear are my gems

``` ruby
gem 'mongoid', git: 'https://github.com/mongoid/mongoid.git'
gem 'bson_ext'
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'fog'
```
### This is carrierwave.rb file content

``` ruby
require 'carrierwave/mongoid'
CarrierWave.configure do |config|
  config.fog_credentials = {
    :provider                 => 'AWS',
    :aws_access_key_id        => ENV['S3_API_KEY_ID'],
    :aws_secret_access_key    => ENV['S3_API_SECRET_KEY'],
    :region                   => ENV['S3_API_REGION'],
    :host                     => 's3.amazonaws.com',
    :endpoint                 => 'https://s3.amazonaws.com' # optional, defaults to nil
  }
  config.fog_directory        = ENV['S3_API_BUCKET']
  config.fog_public           = false                                   # optional, defaults to true
  config.fog_authenticated_url_expiration = 24*60*60
  config.fog_attributes       = {'Cache-Control'=>'max-age=315576000'}  # optional, defaults to {}
end
```
### This is document_file model

``` ruby
class DocumentFile
  include Mongoid::Document
  include Mongoid::Timestamps  

  mount_uploader :file, PdfFileUploader

  field :file,          type: String
  field :verified,      type: Boolean, default: false
  field :expire_date,   type: Date

  belongs_to :document 
  validates_presence_of :file
end
```
### When I upload a file I got this errors

```
Completed 500 Internal Server Error in 66ms

TypeError - no implicit conversion of nil into String:
  fog-core (1.25.0) lib/fog/core/hmac.rb:29:in `block in setup_sha256'
  fog-core (1.25.0) lib/fog/core/hmac.rb:14:in `sign'
  fog (1.25.0) lib/fog/aws/signaturev4.rb:68:in `derived_hmac'
  fog (1.25.0) lib/fog/aws/signaturev4.rb:56:in `signature_components'
  fog (1.25.0) lib/fog/aws/storage.rb:501:in `request'
  fog (1.25.0) lib/fog/aws/requests/storage/put_object.rb:31:in `put_object'
  fog (1.25.0) lib/fog/aws/models/storage/file.rb:208:in `save'
  fog-core (1.25.0) lib/fog/core/collection.rb:50:in `create'
  carrierwave (0.10.0) lib/carrierwave/storage/fog.rb:261:in `store'
  carrierwave (0.10.0) lib/carrierwave/storage/fog.rb:80:in `store!'
  carrierwave (0.10.0) lib/carrierwave/uploader/store.rb:59:in `block in store!'
  carrierwave (0.10.0) lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
  carrierwave (0.10.0) lib/carrierwave/uploader/store.rb:58:in `store!'
  carrierwave (0.10.0) lib/carrierwave/mount.rb:375:in `store!'
  carrierwave (0.10.0) lib/carrierwave/mount.rb:207:in `store_file!'
  activesupport (4.1.0) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.1.0) lib/active_support/callbacks.rb:221:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `run_callbacks'
  app/controllers/dashboard/trial_documents_controller.rb:70:in `update'
```

**Comment by jogiranjith** [comment]
Even i  am facing the same issue when i use multiple file uploads from the controller . 
TypeError - no implicit conversion of nil into String:
  carrierwave (0.10.0) lib/carrierwave/uploader/cache.rb:159:in `cache_path'
  carrierwave (0.10.0) lib/carrierwave/uploader/cache.rb:131:in `block in cache!'
  carrierwave (0.10.0) lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
  carrierwave (0.10.0) lib/carrierwave/uploader/cache.rb:122:in `cache!'
  carrierwave (0.10.0) lib/carrierwave/mount.rb:329:in `cache'
  carrierwave (0.10.0) lib/carrierwave/mount.rb:163:in `avatars='
  carrierwave (0.10.0) lib/carrierwave/orm/activerecord.rb:39:in `avatars='
  activerecord (4.2.0) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
  activerecord (4.2.0) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
  activerecord (4.2.0) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
  activerecord (4.2.0) lib/active_record/core.rb:557:in `init_attributes'
  activerecord (4.2.0) lib/active_record/core.rb:280:in `initialize'
  activerecord (4.2.0) lib/active_record/inheritance.rb:61:in `new'
  activerecord (4.2.0) lib/active_record/reflection.rb:131:in `build_association'
  activerecord (4.2.0) lib/active_record/associations/association.rb:247:in `build_record'
  activerecord (4.2.0) lib/active_record/associations/collection_association.rb:136:in `build'
  activerecord (4.2.0) lib/active_record/associations/collection_proxy.rb:254:in `build'
  app/controllers/applicant/applications_controller.rb:16:in `create'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/a

**Comment by rmm5t** [comment]
Closing stale issues. Dupe of #131?
