### ISSUE TITLE
mount_uploaders

### ISSUE THREAD

**Issue by Nerian** [carrierwaveuploader/carrierwave-mongoid#138]
Hi,

I get an `undefined method mount_uploaders` when I try to use the `mount_uploaders` method. Is there a plan to support this method? Is there somebody working on this I can I take it?

**Comment by TomK32** [comment]
Bump. Too lazy to fix/implement as I'll just use an embedded document for my needs.

**Comment by rmm5t** [comment]
> Bump

This isn't appreciated considering core carrierwave hasn't settled on an implementation yet (there's no official carrierwave release for this feature yet).  With that in mind, I personally have zero use for this feature and little incentive to spend time on it, but I'd be happy to review a pull-request in prep for a future release.

**Comment by TomK32** [comment]
Sorry if the "bump" did sound harsh. Not my intention.

And, there's a hint in my comment for those with the same problem.

**Comment by marigan** [comment]
+1

**Comment by ulitiy** [comment]
I think we should separate `mount_base` method from https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/master/lib/carrierwave/mongoid.rb#L19 here and below. And to write two lines of mount uploader - array field and super. Do you think it will work? I'm not familiar with an architecture, but think that all orm adapters should provide the same DSL.

**Comment by ericraio** [comment]
+1

**Comment by Mohakjuneja** [comment]
Is there any progress on this issue?

**Comment by rmm5t** [comment]
@Mohakjuneja We'd love help with this. #150 started on it, but I cannot merge in a branch that is failing the test suite.  We need a working branch including new tests for the feature.

**Comment by rmm5t** [comment]
* carrierwave-mongoid v0.9.0 is now officially released with carrierwave v0.11 support.
* Note: This release does not yet include `mount_uploaders` support. Waiting on a viable PR for that.

**Comment by iom00** [comment]
is this issued solved? is mount_uploaders usable now?!

**Comment by nPaul** [comment]
NEED mount_uploaders !!!
please make it!

**Comment by leoarnold** [comment]
Hey guys, I just submitted #199 for this issue. Anyone in for some beta testing?

**Comment by vanhob** [comment]
Would love to implement this so happy to help

**Comment by leoarnold** [comment]
@vanhob Awesome. The PR is (to my best knowledge) complete, so you could try:

```ruby
gem 'carrierwave-mongoid', github: 'leoarnold/carrierwave-mongoid', branch: 'leoarnold/feature/mount_uploaders'
```

and start coding something using `mount_uploaders`.

For more reliability, you could fork https://github.com/leoarnold/carrierwave-mongoid and use

```ruby
gem 'carrierwave-mongoid', github: 'vanhob/carrierwave-mongoid', branch: 'leoarnold/feature/mount_uploaders'
```

instead (in order to be independent from unexpected changes).

**Comment by vanhob** [comment]
Hi Leo,

I have done some initial testing and everything works perfect for now.  I have uploaded files successfully and also used it with Zippy and ActionMailer.  The only limitation i have found sofar is compatibility with mount_base64_uploader.

Met vriendelijke groeten,

Bart Vanhoutte

myFaro bvba
Dennenlaan 7
B-3110 Rotselaar
E-mail: info@myfaro.be
Telefoon: 0495 590230
BTW: BE 0668666134
Bank: BE68 1030 4741 9934

**Comment by leoarnold** [comment]
@vanhob Great to hear. As for base64, see this: https://github.com/y9v/carrierwave-base64/issues/79#issuecomment-612859565

**Comment by vanhob** [comment]
hi leoarnold, 

a while back i started using your solution but i did not understand the need to fork the repository.   Now that the gem is no longer available i am stuck.   Is it possible to still clone the repository somehow?

> @vanhob Awesome. The PR is (to my best knowledge) complete, so you could try:
> 
> ```ruby
> gem 'carrierwave-mongoid', github: 'leoarnold/carrierwave-mongoid', branch: 'leoarnold/feature/mount_uploaders'
> ```
> 
> and start coding something using `mount_uploaders`.
> 
> For more reliability, you could fork https://github.com/leoarnold/carrierwave-mongoid and use
> 
> ```ruby
> gem 'carrierwave-mongoid', github: 'vanhob/carrierwave-mongoid', branch: 'leoarnold/feature/mount_uploaders'
> ```
> 
> instead (in order to be independent from unexpected changes).

**Comment by leoarnold** [comment]
@vanhob I left the MongoDB world 6 months ago so I have no stake in this anymore. If you have the [`gh`](https://github.com/cli/cli) tool installed, you can clone this repo here and run `gh pr checkout 199` to obtain the branch you desire. You can then just push it to your GitHub account and do as you please.
