### ISSUE TITLE
Provide utility for treating GridFS files like local files

### ISSUE THREAD

**Issue by themasterchef** [carrierwaveuploader/carrierwave-mongoid#139]
In one of our Jruby Rails apps we use a Java (Mavenised) data crunching library which insists on the use of java.io.File handles (its creator did not have distributed object stores in mind), so we have to get our files out of GridFS and onto local disk, albeit only temporarily. We find ourselves repeating code like the following quite a few times, to transform the `MyModel.some_file_attribute` property (which yields the mounted Carrierwave uploader, which in turn holds a reference to the file on GridFS) into a local temp file.

We would find it worthwhile if either carrierwave-mongoid or mongoid-gridfs (not sure which project is best for this) could be patched to have code similar to that below, although this could probably be improved, and would probably live in a better place than a utility class if incorporated into either project. Suggestions are welcome.

```
##
# For obtaining files which are stored on GridFS
# and using them like local Tempfiles.
class GridfsFileDownloader

  ##
  # Pass this the Carrierwave reference to your file like this:
  # rec = MyModel.new
  # ref = rec.myfileattribute
  # local_temp_file = GridfsFileDownloader.download(ref)
  def self.download carrierwave_file_reference
    # Extract the internal reference to the GridFS file
    the_mongo_file = carrierwave_file_reference.file.grid_file
    
    # Spin up a temp file inside the worker for the Java to actually use
    csv_file = Tempfile.new("gridfs_downloaded_file")

    # Copy contents of remote file into the local temp file
    # Note the use of 'each` from mongoid-gridfs
    # to avoid running out of memory on large files.
    the_mongo_file.each do |chunk|
      csv_file.write chunk
    end

    # Release the handle to the tempfile
    # so that something else can have an exclusive lock on it
    csv_file.close
    
    # Return the handle to it
    return csv_file
  end
end
```

**Comment by rmm5t** [comment]
Just use vanilla carrierwave and ruby for this. There's no need to dive into the internals of this gem or gridfs.

Try something like this instead (untested).

```
Tempfile.open(["file", ".csv"], encoding: "binary") do |f|
  f.write(mongoid_doc.file.read)
  f
end
```
