### ISSUE TITLE
The default chunksize is to large

### ISSUE THREAD

**Issue by eromas** [carrierwaveuploader/carrierwave-mongoid#144]
Hi!
Is there a reason to change the default chunksize?
 self.defaults.chunkSize = 4 * (mb = 2**20)
Sorry for my question, but I can't figure out how to change it.

**Comment by rmm5t** [comment]
This is probably a more appropriate question for https://github.com/ahoward/mongoid-grid_fs (since that's what carrierwave-mongoid) depends on for GridFS.

Something you'll want to address there is, why do you want to change the chunk size?
