### ISSUE TITLE
Latest version not published on Rubygems

### ISSUE THREAD

**Issue by BenSwennen** [carrierwaveuploader/carrierwave-mongoid#158]
Latest commit on master branch (e5c26211c6490f1c39785f0b0accea700fa5d0ef) updates the dependency on carrierwave. However, the version on Rubygems does not reflect this update as this version still depends on carrierwave < 0.11.0

**Comment by rmm5t** [comment]
We're not releasing an official version until we fully support the new features in carrierwave v0.11.0. Specifically `mount_uploaders`. I've been too busy to code this up myself, and no one else has been able to submit us a green pull-request yet, so help is appreciated here.

See #156, #138 , #150, #157

**Comment by rmm5t** [comment]
* carrierwave-mongoid v0.9.0 is now officially released with carrierwave v0.11 support.
* Note: This release does not yet include `mount_uploaders` support. Waiting on a viable PR for that.
