### ISSUE TITLE
Could not view the created model in Rails console. Rails 4 with mongodb and carrierwave-mongoid

### ISSUE THREAD

**Issue by poombavai** [carrierwaveuploader/carrierwave-mongoid#163]
I am getting this error when i try to view my data in console. I used the following command in my console and got this error. 
`Image.all.to_a` 
NameError: uninitialized constant Image::ImagePathUploader

Please help

**Comment by rmm5t** [comment]
Wild guess. Did you restart spring?

**Comment by rmm5t** [comment]
Closing. Lack of follow-up.
