### ISSUE TITLE
Is gem 'mongoid-grid_fs' to be put explicity?  #rails-5

### ISSUE THREAD

**Issue by krazedkrish** [carrierwaveuploader/carrierwave-mongoid#165]
Hi! I am using rails 5, and I just installed carrierwave and carrierwave-mongoid by adding them in the Gemfile. But i cannot find mongoid-grid_fs in Gemfile.lock.

Will I need to add mongoid-grid_fs explicty in the Gemfile as :

gem 'mongoid-grid_fs', github: 'ahoward/mongoid-grid_fs'

or is it no more a dependency in Rails 5 ?

Thanks in advance.

**Comment by rmm5t** [comment]
I'm a little confused by this claim. `carrierwave-mongoid` is definitely still directly dependent upon `mongoid-grid_fs`:
https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/master/carrierwave-mongoid.gemspec#L25

**Comment by krazedkrish** [comment]
Thanks,

I recheck my Gemfiles,
carrierwave-mongoid was by default 0.1.0

I updated it to 0.9.0 and its working good.
