### ISSUE TITLE
How to make carrierwave work with mongo TTL?

### ISSUE THREAD

**Issue by jeffrey008** [carrierwaveuploader/carrierwave-mongoid#169]
Hello, I am trying to add a TTL(time-to-live) to my document.
Here is the look of my model.

``` RUby
class Event
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  mount_uploader :image, MyUploader

    field :expire_at, type: DateTime

    index({ expire_at: 1 }, { expire_after_seconds: 0 })

end
```

Each event has one image. 
I made an event with 60 seconds timespan, after 60 seconds, the event in Mongo is deleted, but the image is still inside its folder.

Here are versions I am using: 

```
carrierwave (1.0.0.beta)
carrierwave-mongoid (0.1.0)
rails (5.0.0.1)
mongo (2.3.0)
mongoid (6.0.0.rc0)
```

Any help is appreciated. Thank you.

**Comment by rmm5t** [comment]
carrierwave-mongoid doesn't know about the TTL expirations and underlying purge within the database. My only (unresearched) guess on this is that you'd have to add a TTL to the associated `fs.files` and `fs.chunks` collection(s) in MongoDB.
