### ISSUE TITLE
Add support for carrierwave 1.0

### ISSUE THREAD

**Issue by rmm5t** [carrierwaveuploader/carrierwave-mongoid#172]
carrierwave 1.0 was released on Christmas Eve. 

Pull-requests are very welcome here.

**Comment by ivanovaleksey** [comment]
Hi @rmm5t,
I tried to create a PR but I am not sure is it enough...
Any comments are welcome.

**Comment by rmm5t** [comment]
@ivanovaleksey Thanks. There's now a new branch named `carrierwave-1.0-support` so that we can work toward carrierwave 1.0 compatibility. It incorporates your PR, and I've also adde some CI config cleanup (eb015492d7776a782e22d26796612d8f597db46b) so we can [better focus the red vs green builds](https://travis-ci.org/carrierwaveuploader/carrierwave-mongoid/builds/191505830).

**Comment by cmavromoustakos** [comment]
Has support for this gem been disncontinued? I am trying to upgrade to rails5.1 and the later carrier wave and just came across this.

Is there anything I can help with?

**Comment by rmm5t** [comment]
@cmavromoustakos I think I'm the only one maintaining this gem, but I don't have any Rails 5.1 projects that use Mongo at the moment. Happy to review pull-requests.

**Comment by Startouf** [comment]
Hello, I have a Rails 5.0 app and I'd be happy to help with support for 1.0 carrierwave as I seem to have some bugs with Carrierwave that may be resolved with 1.0. What's the current status @rmm5t ?

**Comment by rmm5t** [comment]
@Startouf Thanks for the offer. I've been busy with client work over the past few months, but things are a little lighter now. I had carrierwave on my todo list a month or so ago, but then forgot to pick it up when things slowed down, so thank you for the nudge.

Help with PRs and help reviewing and testing existing PRs would be much appreciated.

**Comment by rmm5t** [comment]
carrierwave-mongoid v1.0.0 was just released with carrierwave 1.x support:
https://rubygems.org/gems/carrierwave-mongoid/versions/1.0.0
