### ISSUE TITLE
Help serving file

### ISSUE THREAD

**Issue by Awatatah** [carrierwaveuploader/carrierwave-mongoid#177]
Need a little guidance please. I set this up pretty much default with `AvatarUploader` and the files save fine via Gridfs however, when I use an `image_tag` I get the url that looks like `http://some.domain.com/images/uploaded/users/avatar/:user_id/:file_name` but I cannot access this file via http. I get `No route matches GET...` 
Any ideas? I am new with carrierwave. 

**Rails 5**

**Comment by rmm5t** [comment]
@Awatatah Sorry for the delay here, but the URL-related helpers are just that. You're still responsible for opening up a route in Rails that serves the file at the location specified. 

See https://github.com/carrierwaveuploader/carrierwave-mongoid#route-configuration
