### ISSUE TITLE
v0.1.0 tag refers to wrong commit

### ISSUE THREAD

**Issue by sos4nt** [carrierwaveuploader/carrierwave-mongoid#181]
The [v0.1.0](https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/v0.1.0) tag refers to version 1.0.0:

https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/v0.1.0/lib/carrierwave/mongoid/version.rb
https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/v1.0.0/lib/carrierwave/mongoid/version.rb

The correct commit for v0.1.0 seems to be https://github.com/carrierwaveuploader/carrierwave-mongoid/commit/1bd92e2b28959b15df4b7b016d33b318df1a2689

**Comment by rmm5t** [comment]
That was strange. Not sure how that happened, but thanks for the report. All fixed.
