### ISSUE TITLE
Add support for mongoid 7.x

### ISSUE THREAD

**Issue by sos4nt** [carrierwaveuploader/carrierwave-mongoid#182]
carrierwave-mongoid currently supports mongoid versions [below 7.0](https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/v1.0.0/carrierwave-mongoid.gemspec#L24):
```ruby
s.add_dependency "mongoid", [">= 3.0", "< 7.0"]
```

Please add support for mongoid 7.x

**Comment by rmm5t** [comment]
A PR with passing build matrix is very much welcome.

**Comment by sos4nt** [comment]
Depends on https://github.com/mongoid/mongoid-grid_fs/issues/71

**Comment by rmm5t** [comment]
> Depends on mongoid/mongoid-grid_fs#71

Thanks for the nudge there. Let me take care of getting a new release out for mongoid-grid_fs.

**Comment by rmm5t** [comment]
@thiagofm @mshibuya @jnicklas @elabs-dev @bensie
I'm looking to help make some upgrades to carrierwave-mongoid this week to bring it up to snuff and get a new release deployed.

However, it looks like the Travis-CI builds are no longer active for this repository. Will one of the admins please re-initiate Travis-CI for this repository?
https://travis-ci.org/carrierwaveuploader/carrierwave-mongoid

Thanks!

**Comment by mshibuya** [comment]
Re-activated.

**Comment by rmm5t** [comment]
v1.1.0 was just released adding support for Mongoid 7
