### ISSUE TITLE
Support for Mongoid >= 8.0

### ISSUE THREAD

**Issue by Victorcorcos** [carrierwaveuploader/carrierwave-mongoid#203]
## Issue ⚠️ 

Mongoid 8.0 is released with very important fixes and features, such as [this one](https://jira.mongodb.org/browse/MONGOID-5473).

However, the `carrierwave-mongoid` gem was resolved to 1.3.0, which depends on **mongoid (>= 3.0, < 8)**.

## Steps to Reproduce 👣 

* Gemfile
```rb
gem 'mongoid', '~> 8.0.2'
```

* CMD
```rb
bundle update mongoid
```

* Result
<img width="885" alt="Screen Shot 2022-09-30 at 04 15 34" src="https://user-images.githubusercontent.com/7637806/193213545-ce033f01-82b8-4158-ba6e-05911890f3ce.png">

## Solution 💡 

Could you guys make `carrierwave-mongoid` gem compatible with `mongoid > 8.0`?

Thanks!

**Comment by sos4nt** [comment]
@rmm5t could you take a look into this? The gemspec is preventing an update to the current Mongoid 8.0 version.

**Comment by rgaufman** [comment]
Any update on this please?

**Comment by rmm5t** [comment]
Closed by #210.

v1.4.0 is in the wild: https://rubygems.org/gems/carrierwave-mongoid/versions/1.4.0
