### ISSUE TITLE
Has this project been orphaned?

### ISSUE THREAD

**Issue by sriedel** [carrierwaveuploader/carrierwave-mongoid#208]
Seeing how the 2 PR merges in 2022 have been trivial in nature and the communication from the maintainers on issues and PRs has been sparse at best, I'm wondering if this project should be considered orphaned.

While I don't want to give the impression that I expect unpaid maintainers to keep working on this project, I do believe it would be fair to the remaining users to communicate the current state of the project. Mainly to  allow them to consider alternatives to allow e.g. upgrading their mongoid dependencies and allow them to make longer term plans to move away from a dependency that may no longer be maintained, and can turn into technical debt and/or a liability.

**Comment by bwalton** [comment]
Would it be inappropriate if I offer to fund someones time to get this gem updated? Maybe even just for Mongoid 8 compatibility?

**Comment by rmm5t** [comment]
@bwalton My MondoDB projects have been stagnant lately, and I've been too busy with my work contracts. I probably won't get to this in the immediate future, but if you'd like to re-prioritize my time, I can probably make an effort this week.
https://github.com/sponsors/rmm5t

**Comment by bwalton** [comment]
@rmm5t That sounds like a plan! I'm assuming you'd like to be compensated with more than one snicker bar so I'll shoot you an email asking for details.
