### ISSUE TITLE
Could we please support Mongoid 9?

### ISSUE THREAD

**Issue by rosenfeld-ecore** [carrierwaveuploader/carrierwave-mongoid#213]

**Comment by ipatovanton** [comment]
Mongoid 9 is supported: `s.add_dependency "mongoid", [">= 3.0", "< 9.0"]`

[carrierwave-mongoid.gemspec](https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/master/carrierwave-mongoid.gemspec)

**Comment by rosenfeld** [comment]
As you can see, the specs support less than 9, not 9.

**Comment by ipatovanton** [comment]
> As you can see, the specs support less than 9, not 9.

in practice version 9 works without errors

**Comment by washu** [comment]
bump
